<?php

use Paterns\Creational\Pool\CarPool;
use Paterns\Creational\Pool\Car;
use PHPUnit\Framework\TestCase;

class PoolTest extends TestCase
{
    private CarPool $carPool;
    private array $cars = [];
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carPool = new CarPool();
        $this->cars = $this->carPool->getCars();
    }

    public function testCanRentCar() {
        $rentedCar = $this->carPool->rentCar(1);
        $this->assertInstanceOf(Car::class ,$rentedCar);
    }

    public function testcheckfreeCar() {
        $this->carPool->rentCar(1);
        $freeCar = $this->carPool->freeCar(1);

        $this->assertIsBool($freeCar, $freeCar);
    }
}